// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0akXwrHcsN6TSRSLUFvjG_90wi_VPoCM',
    appId: '1:595837644343:web:3e80d9b98ed21260f659b2',
    messagingSenderId: '595837644343',
    projectId: 'onlineexamapp-f43e2',
    authDomain: 'onlineexamapp-f43e2.firebaseapp.com',
    storageBucket: 'onlineexamapp-f43e2.firebasestorage.app',
    measurementId: 'G-VB2LJY3LZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9MVwoDqiz8eqOgQFnzAyGBjAgz5itZo',
    appId: '1:595837644343:android:fc3de84fbe9f25b0f659b2',
    messagingSenderId: '595837644343',
    projectId: 'onlineexamapp-f43e2',
    storageBucket: 'onlineexamapp-f43e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Aku7hj1RVaz3z5BczR4BUv94apX_jDM',
    appId: '1:595837644343:ios:64aaf2f12b7c05b0f659b2',
    messagingSenderId: '595837644343',
    projectId: 'onlineexamapp-f43e2',
    storageBucket: 'onlineexamapp-f43e2.firebasestorage.app',
    iosClientId: '595837644343-pmutub6angav0mf1n2afoc1f6rs1nr0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineexamsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Aku7hj1RVaz3z5BczR4BUv94apX_jDM',
    appId: '1:595837644343:ios:64aaf2f12b7c05b0f659b2',
    messagingSenderId: '595837644343',
    projectId: 'onlineexamapp-f43e2',
    storageBucket: 'onlineexamapp-f43e2.firebasestorage.app',
    iosClientId: '595837644343-pmutub6angav0mf1n2afoc1f6rs1nr0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineexamsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0akXwrHcsN6TSRSLUFvjG_90wi_VPoCM',
    appId: '1:595837644343:web:931a30f278b6e9ccf659b2',
    messagingSenderId: '595837644343',
    projectId: 'onlineexamapp-f43e2',
    authDomain: 'onlineexamapp-f43e2.firebaseapp.com',
    storageBucket: 'onlineexamapp-f43e2.firebasestorage.app',
    measurementId: 'G-8FEH6CNPK6',
  );
}
